export const PARAGRAPHS: string[] = [
  "en el espacio nadie puede oirte tipear pero todos pueden ver tu cohete despegar manten la calma escribe con precision y veras como las estrellas se alinean a tu favor durante el despegue cada caracter cuenta como un metro de altitud y tu mision es simple subir mas alto que el resto antes de que el reloj llegue a cero respira hondo coloca los dedos sobre las teclas y empieza con la primera letra sin prisa pero sin pausa porque en este vuelo la velocidad importa pero la exactitud importa mas todavia los errores no se atraviesan hay que corregirlos antes de continuar avanzando y por eso conviene mirar al frente leer una palabra entera antes de comenzar a teclearla y dejarse llevar por el ritmo natural del texto la inercia es tu amiga la duda tu enemiga vamos alla",
  "los cohetes mas viejos del programa se identifican por la marca de hollin debajo de las toberas pero todos cuentan la misma historia hubo un dia en que un equipo dijo cinco cuatro tres dos uno y todo lo que estaba en el suelo dejo de estarlo desde entonces cada vez que el contador llega a cero hay alguien que aprieta los punos y mira hacia arriba esperando ver el destello que confirma que la fisica sigue siendo amable con quien la prepara con cuidado en este juego tu cohete es de papel pero el principio se mantiene la masa que aceleras cada caracter correcto suma altitud y la altitud te separa del resto del peloton ten paciencia con los dedos no fuerces el ritmo deja que las palabras vayan saliendo en cascada y veras como la pantalla del host empieza a mostrarte cada vez mas arriba",
  "imagina por un momento que estas en la torre de control con auriculares puestos la voz de un companero te dice que el viento esta limpio y que el cielo aguanta otros tres minutos antes de cerrar la ventana de lanzamiento el equipo entero te mira esperando tu cuenta atras escribir es lo unico que separa al cohete del suelo cada caracter es un newton de empuje y la combustion solo dura unos segundos mas no importa cuanto practiques siempre habra una palabra rara que se atraviesa una tilde escondida una letra que tu indice nunca encuentra a la primera pero ese es justo el reto y la gracia del asunto si todo fuera facil no habria carrera si todo fuera dificil nadie despegaria asi que respira ajusta la postura y empieza despacio que la velocidad llega sola cuando el ritmo se asienta",
  "hay quien dice que tipear es la ultima frontera del oficio del programador pero tambien es la primera de muchos otros oficios escribir codigo escribir cartas escribir ficcion todo pasa por el mismo gesto repetido miles de veces al dia los dedos sobre el teclado los ojos sobre la pantalla y en medio una idea que viaja de un sitio al otro a la velocidad que la mecanica de tus manos permite hoy esa misma mecanica decide cuanto sube tu cohete y a quien adelantas en el ranking lateral no es justo no es injusto es simplemente que algunos llevamos mas anos haciendolo y otros estan empezando ahora si te toca empezar bienvenida si te toca demostrar que sigues en forma adelante el cronometro no distingue entre veteranos y novatos solo cuenta las teclas que aciertan",
  "las primeras misiones tripuladas duraban menos que un partido de futbol pero exigian meses de preparacion docenas de simulacros y la coordinacion impecable de centenares de personas hoy tu mision dura treinta segundos y la unica preparacion que has tenido es esta misma frase asi que aprovechala mira las palabras que vienen anticipa la siguiente antes de terminar la actual no te detengas a admirar lo que ya has escrito eso solo importa cuando el reloj se detiene y hasta entonces solo cuenta lo que falta por delante el espacio en blanco al final del parrafo la barra de progreso que se acerca al borde la sensacion de que todavia puedes meter una palabra mas si te aprietas un poco mas si tus dedos encuentran un compas de marcha que tu cabeza pueda mantener",
];

export function pickParagraph(): string {
  return PARAGRAPHS[Math.floor(Math.random() * PARAGRAPHS.length)];
}
